### ISSUE TITLE
User group | Feedback form | Engagement ideas

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.API#43]
cc: @2fernandez, @MarcusIrmscherSSW, @camillars, @adamcogan, @calumjs, @jontygardner

As per email from @landonmaxwell:

Hi Matt & Anton,
So that we can award SSW Rewards points as an incentive on completion of the form,

1.	Event ID - Use the feedback form’s name to award points per event:
 
Figure: Each feedback form will be titled with “YYYY MM DD Presentation” standard.

2.	Account - Use the email address field to find the user’s account:
 
Figure: Users are awarded points on completion of the form if they add their Rewards App login email address

```[tasklist]
### Tasks
- [x] Update SSW.Rewards.API
- [ ] Update SSW.Rewards.Mobile
- [x] Form integration
```

**Comment by matt-goldman** [comment]
As per my conversation with @AntPolkanov, here is the high-level plan:

Setup Process:

1. Create the achievement in the admin portal
2. Achievement has an "integration ID" property
3. Create the event feedback form, add the integration Id as a property
    a. Can we do this with eg, hidden field?
    b. Looks like we CANNOT do this in Microsoft Forms, but would need to use PowerApps instead
    c. @calumjs - please confirm

User process:

1. User scans the QR, either with their phone camera, or in the app
2. Either way, the form is opened
3. Alternatively, they type the form URL
4. User completes the form
5. If user has an account, they get the points
6. If user does not have an account, they will get the points when they sign up

Changes:

1. Add an IntegrationId property to the Achievement entity
    a. This will be autogenerated, probably something like `ax45Fgsaw34`
2. Update the QR scanner logic.
    a. Currently it looks for a prefix, which determines which endpoint to call (eg achievements vs rewards).
    b. Update this, so that if the prefix is `https:` (current prefixes are `ach:` and `rwd:`), convert the value to a URL and if the Host property matches Microsoft Forms (e.g. `forms.microsoft.com`), open the URL in the device browser
    c. **NOTE:** Would be good to pass the user's email address as a query parameter to pre-populate it
    d: Looks like this is **NOT** possible in Microsoft Forms. Would need to be done in PowerApps.
    e: @calumjs - please confirm
3. Create the integration to send the `integrationId` and the user's email address to the SSW.Rewards API upon completion of the form
    a. Can this be done with Microsoft Forms? Or does this also need a PowerApp?
    b. @calumjs - please confirm.
4. A new API route to handle form callbacks    
    a. It will look up the achievement using the Integration Id.
    b. It will look up the user using their email address (as entered on the form)
    c. If the user exists, check to see whether they already have this achievement
    d. If the user has not claimed the achievement already, award it
    e. If the user does not exist, add an entry to the `UnclaimedAchievements` table
    f. Check to see that the `achievementId` and email address combo does not already exist in the table first
5. Add the unclaimed achievements table, e.g.:
    a. `UserEmail`
    b. `AchievementId`
    d. `AwardedOn`
6. When a user signs up, check the unclaimed achievements table for any rows matching their email address
    a. If any found, assign them the achievement and set the `AwardedOn` property

**Comment by AntPolkanov** [comment]
@calumjs has suggested to look into Power Pages as we cannot do this with Microsoft Forms. It will incur some costs of at least $75 for 500 users/site/month ([PowerPages Pricing](https://powerpages.microsoft.com/en-us/pricing/)). 

He also proposed to consider a custom solution.

**Comment by matt-goldman** [comment]
cc: @adamcogan @calumjs

Hey @AntPolkanov, I have a working prototype of this with Google Forms. I will record a done video showing it in action and send to Adam for consideration/approval.
