### ISSUE TITLE
API deployment pipelines

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.API#50]
## CICD for API deployment

Have the Rewards API pipelines handled by GitHub Workflows.

### Acceptance Criteria
- [ ] Automatically deploy to Dev environment on merge to Main
- [ ] Able to deploy to Dev, Staging and Production via manual GitHub Workflow dispatch

**Comment by matt-goldman** [comment]
Closed by https://github.com/SSWConsulting/SSW.Rewards.API/pull/6
